### ISSUE TITLE
INFLATE EXCEPTION

### ISSUE THREAD

**Issue by Dave181295** [travijuu/NumberPicker#20]
Hours I'm searching for solutions.. please where is the problem ?
` android.view.InflateException: Binary XML file line #93: Binary XML file line #93: Error inflating class com.travijuu.numberpicker.library.NumberPicker
    Caused by: android.view.InflateException: Binary XML file line #93: Error inflating class com.travijuu.numberpicker.library.NumberPicker
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)`

**Comment by sasmitadn** [comment]
If you copy-paste **@layout/number_picker_custom_layout** from the readme, you must **change TextView to EditText**
